[package]
name = "SNTPing"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.4"
pnet = "0.35.0"
rand = "0.8.5"
reqwest = { version="0.12.8", features = ["blocking", "json"] }
futures-io = { version = "0.2.0-beta" }
chrono = "0.4.38"
